spring:
  datasource:
    password: 12345
    url: jdbc:mysql://localhost:3306/mobilele?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: TRUE
        show_sql: TRUE
    hibernate:
      ddl-auto: update
    open-in-view: false
logging:
  level:
    org: warn
    blog: warn
    hibernate:
      SQL: debug
      type:
        descriptor: trace



